name: Daily Blog Summary Bot Test

on:
  # 手動でいつでも実行できるようにする設定
  workflow_dispatch:
  # 毎日日本時間の朝9:00（世界標準時の0:00）に定期実行する設定
  schedule:
    - cron: '0 0 * * *'

jobs:
  test_rss:
    runs-on: ubuntu-latest
    steps:
      - name: Check Angerme Blog RSS
        run: |
          curl -I https://rssblog.ameba.jp/angerme-new/rss20.xml
